# Generated by Django 6.1.1 on 2026-09-17 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(default=django.utils.timezone.localdate)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Who this particular bill belongs to — matters when a subscription was transferred mid-month.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='subscriptions.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('subscription', 'year', 'month', 'customer')},
        ),
        migrations.CreateModel(
            name='OutboxNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='sms', max_length=20)),
                ('message', models.TextField()),
                ('delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='subscriptions.customer')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='subscriptions.customer')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='subscriptions.subscription')),
                ('to_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='subscriptions.customer')),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
    ]
